// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbenlzaaoszdeflqogsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiZW5semFhb3N6ZGVmbHFvZ3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3ODQzMDgsImV4cCI6MjA3NTM2MDMwOH0._p8n3WxHkqQvO5PuKJ3O4SceWPmdnHVvXlAvBI9hJIk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});